# Generated by Django 3.1.2 on 2020-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asystent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_i_nazwisko', models.CharField(max_length=200, null=True)),
                ('telefon', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
