# Generated by Django 3.1.2 on 2020-10-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0002_asystent_dom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, null=True)),
                ('dzielnica', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Lista rezerwowa', 'Lista rezerwowa'), ('Aktywny', 'Aktywny'), ('Zmarły', 'Zmarły'), ('Rezygnacja', 'Rezygnacja')], max_length=200, null=True)),
                ('imie_i_nazwisko', models.CharField(max_length=200, null=True)),
                ('telefon', models.CharField(max_length=200, null=True)),
                ('opiekun', models.CharField(max_length=200, null=True)),
                ('telefon_opiekuna', models.CharField(max_length=200, null=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True, null=True)),
                ('dom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacjenci.dom')),
            ],
        ),
    ]
