# Generated by Django 3.1.2 on 2020-10-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0004_auto_20201018_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='nr_IMEI',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
