# Generated by Django 3.1.2 on 2020-10-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0005_pacjent_nr_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zgloszenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Nowe', 'Nowe'), ('W trakcie', 'W trakcie'), ('Rozwiązane', 'Rozwiązane')], max_length=200, null=True)),
                ('rodzaj', models.CharField(choices=[('Awaria', 'Awaria'), ('Rezygnacja', 'Rezygnacja'), ('Inne', 'Inne')], max_length=200, null=True)),
                ('opis', models.CharField(max_length=500, null=True)),
                ('asystent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacjenci.asystent')),
                ('pacjent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacjenci.pacjent')),
            ],
        ),
    ]
