# Generated by Django 3.1.2 on 2020-10-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0007_auto_20201022_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zgloszenie',
            options={'verbose_name': 'Zgłoszenie', 'verbose_name_plural': 'Zgłoszenia'},
        ),
    ]
