# Generated by Django 3.1.2 on 2020-11-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0009_zgloszenie_data_dodania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacjent',
            name='opiekun',
        ),
        migrations.RemoveField(
            model_name='pacjent',
            name='telefon_opiekuna',
        ),
        migrations.RemoveField(
            model_name='zgloszenie',
            name='asystent',
        ),
    ]
